package schoolmanagementsystem;

import java.awt.EventQueue;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Arrays;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

public class StudentModule extends ApplicationWindow {

	private JLabel label;
	private JTable table;
	private JButton goBack;
	private JButton addStudent;
	private JButton modifyFee;
	private JButton edit;
	private JButton delete;
	private JButton search;
	private JComboBox listAttributes;
	private JTextField textToSearch;
	private JScrollPane scrollPane;
	private JPanel middlePanel;
	private JPanel bottomPanel;

	public StudentModule() {
		this.initComponents();
	}

	private void initComponents() {
		this.label = new JLabel("Search & Edit Students");
		this.label.setFont(headerFont);
		this.label.setHorizontalAlignment(SwingConstants.CENTER);
		this.goBack = new JButton("Back");
		this.addStudent = new JButton("Add");
		this.search = new JButton("Search");
		this.modifyFee = new JButton("Modify Fee");
		this.edit = new JButton("Edit");
		this.delete = new JButton("Delete");
		String[] columns = { "Attribute 1", "Attribute 2" };
		this.listAttributes = new JComboBox(columns);
		this.textToSearch = new JTextField();
		this.bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
		this.middlePanel = new JPanel(new GridBagLayout());

		// TODO Add functionality
		String[][] values = { { "Example 1", "Example 2" }, { "Example 3", "Example 4" } };
		this.table = new JTable(values, columns);
		this.scrollPane = new JScrollPane(this.table);

		this.goBack.addActionListener(event -> showWindow(new HomePage()));
		
		GridBagConstraints constraints = new GridBagConstraints();
		constraints.fill = GridBagConstraints.HORIZONTAL;
		constraints.gridx = 0;
		constraints.gridy = 0;
		this.middlePanel.add(this.listAttributes, constraints);
		constraints.weightx = 1.0;
		constraints.gridx++;
		this.middlePanel.add(this.textToSearch, constraints);
		constraints.weightx = 0.0;
		constraints.gridx++;
		this.middlePanel.add(this.search, constraints);
		constraints.gridx = 0;
		constraints.gridwidth = 3;
		constraints.gridy++;
		this.middlePanel.add(this.scrollPane, constraints);
		
		this.bottomPanel.add(this.goBack);
		this.bottomPanel.add(this.addStudent);
		this.bottomPanel.add(this.modifyFee);
		this.bottomPanel.add(this.edit);
		this.bottomPanel.add(this.delete);

		getContentPane().add(this.label, BorderLayout.NORTH);
		getContentPane().add(this.middlePanel, BorderLayout.CENTER);
		getContentPane().add(this.bottomPanel, BorderLayout.SOUTH);
	}

	public static void main(String[] args) {
		EventQueue.invokeLater(() -> new StudentModule().showWindow());
	}

	private void updateTable(String sql) {

	}
	/**
	 * Creates new form SDStud public SearchStudent() { initComponents(); }
	 * 
	 * /** This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @SuppressWarnings("unchecked") //
	 * <editor-fold defaultstate="collapsed" desc="Generated
	 * Code">//GEN-BEGIN:initComponents private void initComponents() {
	 * 
	 * jLabel1 = new javax.swing.JLabel(); jLabel2 = new javax.swing.JLabel();
	 * jScrollPane1 = new javax.swing.JScrollPane(); studTable = new
	 * javax.swing.JTable(); jButton1 = new javax.swing.JButton(); jLabel3 = new
	 * javax.swing.JLabel(); sid = new javax.swing.JTextField(); jButton2 = new
	 * javax.swing.JButton(); jLabel4 = new javax.swing.JLabel();
	 * 
	 * jLabel1.setText("jLabel1");
	 * 
	 * setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	 * 
	 * jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
	 * jLabel2.setText("Search & Delete Students");
	 * 
	 * studTable.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); //
	 * NOI18N studTable.setModel(new javax.swing.table.DefaultTableModel( new Object
	 * [][] { {null, null, null, null, null, null, null, null}, {null, null, null,
	 * null, null, null, null, null}, {null, null, null, null, null, null, null,
	 * null}, {null, null, null, null, null, null, null, null} }, new String [] {
	 * "ID", "NAME", "GUARDIAN NAME", "PHONE", "GUARDIAN PHONE", "CLASS", "ROLL
	 * NUMBER", "ADDRESS" } )); jScrollPane1.setViewportView(studTable);
	 * 
	 * jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); //
	 * NOI18N jButton1.setText("SEARCH"); jButton1.addActionListener(new
	 * java.awt.event.ActionListener() { public void
	 * actionPerformed(java.awt.event.ActionEvent evt) {
	 * jButton1ActionPerformed(evt); } });
	 * 
	 * jLabel3.setText("To Delete, Insert the ID:");
	 * 
	 * jButton2.setText("Delete"); jButton2.addActionListener(new
	 * java.awt.event.ActionListener() { public void
	 * actionPerformed(java.awt.event.ActionEvent evt) {
	 * jButton2ActionPerformed(evt); } });
	 * 
	 * jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
	 * jLabel4.setForeground(new java.awt.Color(0, 0, 204));
	 * jLabel4.setText("BACK"); jLabel4.addMouseListener(new
	 * java.awt.event.MouseAdapter() { public void
	 * mouseClicked(java.awt.event.MouseEvent evt) { jLabel4MouseClicked(evt); } });
	 * 
	 * javax.swing.GroupLayout layout = new
	 * javax.swing.GroupLayout(getContentPane());
	 * getContentPane().setLayout(layout); layout.setHorizontalGroup(
	 * layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 * .addGroup(layout.createSequentialGroup() .addComponent(jScrollPane1,
	 * javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
	 * .addContainerGap()) .addGroup(layout.createSequentialGroup()
	 * .addContainerGap()
	 * .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 * .addGroup(layout.createSequentialGroup()
	 * .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 * .addComponent(jLabel3) .addGroup(layout.createSequentialGroup()
	 * .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 68,
	 * javax.swing.GroupLayout.PREFERRED_SIZE)
	 * .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	 * .addComponent(jButton2))) .addGap(0, 0, Short.MAX_VALUE))
	 * .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
	 * layout.createSequentialGroup() .addGap(0, 0, Short.MAX_VALUE)
	 * .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 * .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
	 * layout.createSequentialGroup() .addComponent(jButton1) .addGap(263, 263,
	 * 263)) .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
	 * layout.createSequentialGroup() .addComponent(jLabel2) .addGap(89, 89, 89)
	 * .addComponent(jLabel4) .addGap(23, 23, 23)))))) ); layout.setVerticalGroup(
	 * layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 * .addGroup(layout.createSequentialGroup() .addContainerGap()
	 * .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 * .addGroup(layout.createSequentialGroup() .addComponent(jLabel4) .addGap(30,
	 * 30, 30)) .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
	 * layout.createSequentialGroup() .addComponent(jLabel2)
	 * .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
	 * .addComponent(jButton1)
	 * .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	 * .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
	 * javax.swing.GroupLayout.PREFERRED_SIZE) .addGap(28, 28, 28)
	 * .addComponent(jLabel3)
	 * .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	 * .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	 * .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE,
	 * javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	 * .addComponent(jButton2))
	 * .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)) );
	 * 
	 * pack(); }// </editor-fold>//GEN-END:initComponents
	 * 
	 * private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	 * {//GEN-FIRST:event_jButton1ActionPerformed // TODO add your handling code
	 * here: try{ Class.forName("com.mysql.jdbc.Driver"); Connection conn =
	 * DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");
	 * Statement st=conn.createStatement(); String sql= "select * from stureg";
	 * PreparedStatement ptst= conn.prepareStatement(sql); ResultSet rs=
	 * ptst.executeQuery(); DefaultTableModel
	 * tm=(DefaultTableModel)studTable.getModel(); tm.setRowCount(0);
	 * while(rs.next()){ Object o[]=
	 * {rs.getInt("ID"),rs.getString("Name"),rs.getString("fname"),rs.getInt("phone"),
	 * rs.getInt("fatherphone"),rs.getString("class"),rs.getString("roll"),rs.getString("address")};
	 * tm.addRow(o); }
	 * 
	 * }catch (Exception e){ JOptionPane.showMessageDialog(null, e); }
	 * 
	 * }//GEN-LAST:event_jButton1ActionPerformed
	 * 
	 * private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
	 * {//GEN-FIRST:event_jButton2ActionPerformed // TODO add your handling code
	 * here:
	 * 
	 * String sd= sid.getText(); try{ Class.forName("com.mysql.jdbc.Driver");
	 * Connection conn =
	 * DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");
	 * Statement st=conn.createStatement(); String sql= "DELETE FROM `stureg` WHERE
	 * ID="+sd; PreparedStatement ptst= conn.prepareStatement(sql);
	 * ptst.executeUpdate(); JOptionPane.showMessageDialog(null, "Data has been
	 * removed"); conn.close(); sid.setText(""); }catch(Exception e){
	 * JOptionPane.showMessageDialog(null, e); }
	 * }//GEN-LAST:event_jButton2ActionPerformed
	 * 
	 * private void jLabel4MouseClicked(java.awt.event.MouseEvent evt)
	 * {//GEN-FIRST:event_jLabel4MouseClicked // TODO add your handling code here:
	 * StudentModule obj=new StudentModule(); obj.setVisible(true); dispose();
	 * }//GEN-LAST:event_jLabel4MouseClicked
	 * 
	 * 
	 * public static void main(String args[]) { /* Set the Nimbus look and feel
	 */
	// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
	 * look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 * 
	 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
	 * (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.
	 * util.logging.Level.SEVERE, null, ex); } catch (InstantiationException ex) {
	 * java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.
	 * util.logging.Level.SEVERE, null, ex); } catch (IllegalAccessException ex) {
	 * java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.
	 * util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.
	 * util.logging.Level.SEVERE, null, ex); } //</editor-fold>
	 * 
	 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
	 * SearchStudent().setVisible(true); } }); }
	 * 
	 * // Variables declaration - do not modify//GEN-BEGIN:variables private
	 * javax.swing.JButton jButton1; private javax.swing.JButton jButton2; private
	 * javax.swing.JLabel jLabel1; private javax.swing.JLabel jLabel2; private
	 * javax.swing.JLabel jLabel3; private javax.swing.JLabel jLabel4; private
	 * javax.swing.JScrollPane jScrollPane1; private javax.swing.JTextField sid;
	 * private javax.swing.JTable studTable; // End of variables
	 * declaration//GEN-END:variables
	 */
}

/*
package schoolmanagementsystem;

import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.BoxLayout;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.Component;

public class StudentModule extends ApplicationWindow {

	private JLabel label;
	private JButton addStudent;
	private JButton searchStudent;
	private JButton goBack;
	private JPanel panel;

	public StudentModule() {
		this.initComponents();
	}

	private void initComponents() {
		this.label = new JLabel("Manage Students");
		this.label.setFont(headerFont);
		this.label.setHorizontalAlignment(SwingConstants.CENTER);
		this.addStudent = new JButton("Add Student");
		this.searchStudent = new JButton("Search & Edit Student");
		this.goBack = new JButton("Back");
		this.panel = new JPanel();
		this.panel.setLayout(new BoxLayout(this.panel, BoxLayout.PAGE_AXIS));

		this.addStudent.addActionListener(event -> showWindow(new AddStudent()));
		this.searchStudent.addActionListener(event -> showWindow(new SearchStudent()));
		this.goBack.addActionListener(event -> showWindow(new HomePage()));
		
		this.addStudent.setAlignmentX(Component.CENTER_ALIGNMENT);
		this.searchStudent.setAlignmentX(Component.CENTER_ALIGNMENT);
		this.goBack.setAlignmentX(Component.CENTER_ALIGNMENT);
		
		this.panel.add(this.addStudent);
		this.panel.add(this.searchStudent);
		this.panel.add(this.goBack);

		getContentPane().add(this.label, BorderLayout.NORTH);
		getContentPane().add(this.panel, BorderLayout.CENTER);
	}

	public static void main(String args[]) {
		EventQueue.invokeLater(() -> new StudentModule().showWindow());
	}
}
*/