package schoolmanagementsystem;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

public class TeacherModule extends ApplicationWindow {


	private JLabel label;
	private JTable table;
	private JButton goBack;
	private JButton addTeacher;
	private JButton edit;
	private JButton delete;
	private JButton search;
	private JComboBox listAttributes;
	private JTextField textToSearch;
	private JScrollPane scrollPane;
	private JPanel middlePanel;
	private JPanel bottomPanel;

	public TeacherModule() {
		this.initComponents();
	}

	private void initComponents() {
		this.label = new JLabel("Search & Edit Teachers");
		this.label.setFont(headerFont);
		this.label.setHorizontalAlignment(SwingConstants.CENTER);
		this.goBack = new JButton("Back");
		this.addTeacher = new JButton("Add");
		this.search = new JButton("Search");
		this.edit = new JButton("Edit");
		this.delete = new JButton("Fire");
		String[] columns = { "Attribute 1", "Attribute 2" };
		this.listAttributes = new JComboBox(columns);
		this.textToSearch = new JTextField();
		this.bottomPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
		this.middlePanel = new JPanel(new GridBagLayout());

		// TODO Add functionality
		String[][] values = { { "Example 1", "Example 2" }, { "Example 3", "Example 4" } };
		this.table = new JTable(values, columns);
		this.scrollPane = new JScrollPane(this.table);

		this.goBack.addActionListener(event -> showWindow(new HomePage()));
		
		GridBagConstraints constraints = new GridBagConstraints();
		constraints.fill = GridBagConstraints.HORIZONTAL;
		constraints.weightx = 0.0;
		constraints.gridx = 0;
		constraints.gridy = 0;
		this.middlePanel.add(this.listAttributes, constraints);
		constraints.weightx = 1.0;
		constraints.gridx++;
		this.middlePanel.add(this.textToSearch, constraints);
		constraints.weightx = 0.0;
		constraints.gridx++;
		this.middlePanel.add(this.search, constraints);
		constraints.gridx = 0;
		constraints.gridwidth = 3;
		constraints.gridy++;
		this.middlePanel.add(this.scrollPane, constraints);
		
		this.bottomPanel.add(this.goBack);
		this.bottomPanel.add(this.addTeacher);
		this.bottomPanel.add(this.edit);
		this.bottomPanel.add(this.delete);

		getContentPane().add(this.label, BorderLayout.NORTH);
		getContentPane().add(this.middlePanel, BorderLayout.CENTER);
		getContentPane().add(this.bottomPanel, BorderLayout.SOUTH);
	}

	public static void main(String[] args) {
		EventQueue.invokeLater(() -> new TeacherModule().showWindow());
	}

	private void updateTable(String sql) {

	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Fire Teachers");

        jLabel2.setText("To fire a teacher, enter their ID:");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("BACK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        TeacherModule obj =new TeacherModule();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tid= id.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn= DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root","");
            String sql="delete from `addteacher` WHERE id="+tid;
            PreparedStatement ptst=conn.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data has been removed!");
            conn.close();
         }catch (Exception e){
             JOptionPane.showMessageDialog(this, e);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
     * 
     */
}
/*
package schoolmanagementsystem;

import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.BoxLayout;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.EventQueue;

public class TeacherModule extends ApplicationWindow {

	private JLabel label;
	private JButton addTeacher;
	private JButton searchTeacher;
	private JButton goBack;
	private JPanel panel;

	public TeacherModule() {
		this.initComponents();
	}

	private void initComponents() {
		this.label = new JLabel("Manage Teachers");
		this.label.setFont(headerFont);
		this.label.setHorizontalAlignment(SwingConstants.CENTER);
		this.addTeacher = new JButton("Add Teacher");
		this.searchTeacher = new JButton("Search & Edit Teacher");
		this.goBack = new JButton("Back");
		this.panel = new JPanel();
		this.panel.setLayout(new BoxLayout(this.panel, BoxLayout.PAGE_AXIS));

		this.addTeacher.addActionListener(event -> showWindow(new AddTeacher()));
		this.searchTeacher.addActionListener(event -> showWindow(new SearchTeacher()));
		this.goBack.addActionListener(event -> showWindow(new HomePage()));

		this.addTeacher.setAlignmentX(Component.CENTER_ALIGNMENT);
		this.searchTeacher.setAlignmentX(Component.CENTER_ALIGNMENT);
		this.goBack.setAlignmentX(Component.CENTER_ALIGNMENT);
		
		this.panel.add(this.addTeacher);
		this.panel.add(this.searchTeacher);
		this.panel.add(this.goBack);

		getContentPane().add(this.label, BorderLayout.NORTH);
		getContentPane().add(this.panel, BorderLayout.CENTER);
	}

	public static void main(String args[]) {
		EventQueue.invokeLater(() -> new TeacherModule().showWindow());
	}
}
*/